#logging:
#  level: debug

server:
  port: 8011

spring:
  ## 配置多個配置文件


  ## resources 配置资源文件；
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false


  ## REDIS (RedisProperties) redis基本配置；
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 106.14.146.232
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: aliyunredis
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
        max-active: -300
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: -100
        # 连接池中的最小空闲连接
        min-idle: -0
    # 连接超时时间（毫秒）
    timeout: 100000

  ## mail基本配置；
  mail:
    # 设置邮箱主机
    host: smtpdm.aliyun.com
    # 设置端口
    port: 465
    # 设置用户名
    username: sys@info.ixxjd.com
    # 设置密码
    password: aliMail513inFo
    properties:
      mail:
        smtp:
          # 设置是否需要认证，如果为true,那么用户名和密码就必须的
          auth: true
          # STARTTLS[1] 是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL）
          starttls:
            enable: true
            required: true
          # aliyun邮件推送服务
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

  http:
    # 文件上传数据大小配置
    multipart:
      # 文件最大大小
      maxFileSize: 10MB
      # 总数据上传大小
      maxRequestSize: 100MB

  ########################################################
  ### MYBATIS  mybatis基本配置；
  ########################################################
mybatis:
  mapper-locations: classpath:sqlMap/*.xml
  type-aliases-package: com.ixxjd.info.common.security.domain


  ########################################################
  ### KAPTCHA  kaptcha基本配置；
  ########################################################
kaptcha:
  session:
    key: kaptcha.code
  #border: no
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
  obscurificator:
    impl: com.google.code.kaptcha.impl.WaterRipple
  #要噪点
  noise:
    impl: com.google.code.kaptcha.impl.DefaultNoise
  image:
    width: 200
    height: 50
  textproducer:
    font:
      size: 40
      color: black
    char:
      length: 5
      space: 5

#缓存图片:http://www.kafeitu.me/activiti/2013/02/14/improve-performance-for-reading-diagram.html
export:
  diagram:
    path: /workflow/kft-activiti-demo
  http:
    url: http://localhost:10000
  activityFontName: 宋体
  labelFontName: 宋体